import type { ZoneSeed } from './types';

export const defaultZones: ZoneSeed[] = [
  { id: 'A1', level: 'ชั้น 1', color: 'blue', top: '44%', left: '36%', width: '7%', height: '10%' },
  { id: 'A2', level: 'ชั้น 1', color: 'blue', top: '44%', left: '45.5%', width: '7%', height: '10%' },
  { id: 'A3', level: 'ชั้น 1', color: 'blue', top: '44%', left: '55%', width: '7%', height: '10%' },
  { id: 'A4', level: 'ชั้น 1', color: 'blue', top: '44%', left: '64.5%', width: '7%', height: '10%' },
  { id: 'B1', level: 'ชั้น 1', color: 'blue', top: '56%', left: '36%', width: '7%', height: '10%' },
  { id: 'B2', level: 'ชั้น 1', color: 'blue', top: '56%', left: '45.5%', width: '7%', height: '10%' },
  { id: 'B3', level: 'ชั้น 1', color: 'blue', top: '56%', left: '55%', width: '7%', height: '10%' },
  { id: 'B4', level: 'ชั้น 1', color: 'blue', top: '56%', left: '64.5%', width: '7%', height: '10%' },
  { id: 'C1', level: 'ชั้น 1', color: 'blue', top: '65%', left: '43%', width: '7%', height: '4%' },
  { id: 'C2', level: 'ชั้น 1', color: 'blue', top: '65%', left: '57%', width: '7%', height: '4%' },
  { id: 'SB', level: 'ชั้น 2', color: 'yellow', top: '38%', left: '26%', width: '5%', height: '5%' },
  { id: 'SC', level: 'ชั้น 2', color: 'yellow', top: '45%', left: '26%', width: '5%', height: '5%' },
  { id: 'SD', level: 'ชั้น 2', color: 'yellow', top: '53%', left: '26%', width: '5%', height: '5%' },
  { id: 'SE', level: 'ชั้น 2', color: 'yellow', top: '61%', left: '28%', width: '5%', height: '5%' },
  { id: 'SF', level: 'ชั้น 2', color: 'yellow', top: '67%', left: '34%', width: '6%', height: '4%' },
  { id: 'SG', level: 'ชั้น 2', color: 'yellow', top: '71%', left: '41%', width: '7%', height: '4%' },
  { id: 'SH', level: 'ชั้น 2', color: 'yellow', top: '71%', left: '50%', width: '7%', height: '4%' },
  { id: 'SI', level: 'ชั้น 2', color: 'yellow', top: '71%', left: '59%', width: '7%', height: '4%' },
  { id: 'SJ', level: 'ชั้น 2', color: 'yellow', top: '67%', left: '66%', width: '6%', height: '4%' },
  { id: 'SK', level: 'ชั้น 2', color: 'yellow', top: '61%', left: '72%', width: '5%', height: '5%' },
  { id: 'SL', level: 'ชั้น 2', color: 'yellow', top: '53%', left: '74%', width: '5%', height: '5%' },
  { id: 'SM', level: 'ชั้น 2', color: 'yellow', top: '45%', left: '74%', width: '5%', height: '5%' },
  { id: 'SN', level: 'ชั้น 2', color: 'yellow', top: '38%', left: '74%', width: '5%', height: '5%' },
  { id: 'B', level: 'ชั้น 3', color: 'red', top: '35%', left: '16%', width: '6%', height: '6%' },
  { id: 'C', level: 'ชั้น 3', color: 'red', top: '43%', left: '16%', width: '6%', height: '6%' },
  { id: 'D', level: 'ชั้น 3', color: 'red', top: '51%', left: '16%', width: '6%', height: '6%' },
  { id: 'E', level: 'ชั้น 3', color: 'red', top: '59%', left: '17%', width: '6%', height: '6%' },
  { id: 'F', level: 'ชั้น 3', color: 'red', top: '66%', left: '21%', width: '6%', height: '6%' },
  { id: 'G', level: 'ชั้น 3', color: 'red', top: '71%', left: '27%', width: '6%', height: '6%' },
  { id: 'H', level: 'ชั้น 3', color: 'red', top: '75%', left: '33%', width: '6%', height: '6%' },
  { id: 'I', level: 'ชั้น 3', color: 'red', top: '79%', left: '40%', width: '6%', height: '6%' },
  { id: 'J', level: 'ชั้น 3', color: 'red', top: '80%', left: '46%', width: '6%', height: '6%' },
  { id: 'K', level: 'ชั้น 3', color: 'red', top: '80%', left: '54%', width: '6%', height: '6%' },
  { id: 'L', level: 'ชั้น 3', color: 'red', top: '79%', left: '60%', width: '6%', height: '6%' },
  { id: 'M', level: 'ชั้น 3', color: 'red', top: '75%', left: '67%', width: '6%', height: '6%' },
  { id: 'N', level: 'ชั้น 3', color: 'red', top: '71%', left: '73%', width: '6%', height: '6%' },
  { id: 'O', level: 'ชั้น 3', color: 'red', top: '66%', left: '79%', width: '6%', height: '6%' },
  { id: 'P', level: 'ชั้น 3', color: 'red', top: '59%', left: '83%', width: '6%', height: '6%' },
  { id: 'Q', level: 'ชั้น 3', color: 'red', top: '51%', left: '84%', width: '6%', height: '6%' },
  { id: 'R', level: 'ชั้น 3', color: 'red', top: '43%', left: '84%', width: '6%', height: '6%' },
  { id: 'S', level: 'ชั้น 3', color: 'red', top: '35%', left: '84%', width: '6%', height: '6%' },
  { id: 'T', level: 'ชั้น 3', color: 'red', top: '28%', left: '84%', width: '6%', height: '6%' },
];
